BC-461: Updated zap_scan

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -166,14 +166,28 @@ jobs:
           SENTRY_ENVIRONMENT: local
           SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
           REDIS_URL: http://localhost:6379
+          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
         run: |
           echo "Running application..."
           docker compose up -d wiremock redis
           ./gradlew bootRun &
-          echo "Waiting for application..."
-          until curl -s http://host.docker.internal:8182/actuator/health | grep '"status":"UP"'; do
-            sleep 5
+          
+          url="http://host.docker.internal:8182/actuator/health"
+          retries=20
+          
+          for i in $(seq 1 $retries); do
+            echo "INFO: Checking application health (attempt $i of $retries)..."
+            if curl -sf "$url" | grep -q '"status":"UP"'; then
+              echo "INFO: Application is healthy";
+              exit 0;
+            fi
+            sleep 2
           done
+          
+          echo "ERROR: Application did not start"           
+          exit 1
       - name: ZAP Scan
         uses: zaproxy/action-full-scan@v0.13.0
         with:
